# Generated by Django 5.0.7 on 2024-07-18 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserServices', '0003_alter_modules_module_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modules',
            name='module_description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
